name: "Request new repository"
description: "Request creation of a GitHub repository"
title: "Create Repo: {repo-name}"
labels:
  - administration
  - createrepo
body:
  - type: input
    id: repo-name
    required: true
    attributes:
      label: "Repository name"
      description: "Name of the new repo"
      required: true
  - type: dropdown
    id: visibility
    required: true
    attributes:
      label: "Visibility"
      description: "Choose public or private"
      options:
        - public
        - private
      required: true
  - type: input
    id: repo-description
    attributes:
      label: "Description"
      description: "Short description for the repository"
      required: false
