name: "Request new repository"
description: "Request creation of a GitHub repository"
title: "Create Repo: {repo-name}"
labels:
  - administration
  - createrepo
body:
  - type: input
    id: repo-name
    attributes:
      label: "Repository name"
      description: "Name of the new repo (use lowercase, hyphens)"
      placeholder: "example-repo"
    validations:
      required: true
  - type: dropdown
    id: visibility
    attributes:
      label: "Visibility"
      options:
        - label: "Public"
          value: public
        - label: "Private"
          value: private
    validations:
      required: true
  - type: input
    id: repo-description
    attributes:
      label: "Description"
      description: "Short description for the repository"
      placeholder: "Short project summary"