name: "Request new repository"
description: "Request creation of a GitHub repository"
title: "Create Repo: {repo-name}"
labels:
  - administration
  - createrepo
body:
  - type: input
    id: repo-name
    attributes:
      label: "Repository name"
      description: "Name of the new repo (lowercase, hyphens)"
      placeholder: "example-repo"
    validations:
      min_length: 1
  - type: dropdown
    id: visibility
    default: "public"
    attributes:
      label: "Visibility"
      description: "Choose public or private"
      options:
        - label: "Public"
          value: "public"
        - label: "Private"
          value: "private"
  - type: input
    id: repo-description
    attributes:
      label: "Description"
      description: "Short description for the repository"
      placeholder: "Short project summary"